export type RedeemValue = { points: number; value: number };
export type Experience = {
  name: string;
  description: string;
  category: string;
  earnMultiplier: string;
  redeemValues: RedeemValue[];
  link: string;
};

export const experiences: Experience[] = [
  {
    name: "Nibs Etc.",
    description: "Granola that's good for you and the planet",
    category: "Shopping",
    earnMultiplier: "5x",
    redeemValues: [
      { points: 1755, value: 15 },
      { points: 3510, value: 30 },
      { points: 7020, value: 60 },
    ],
    link: "https://nibsetc.com",
  },
  {
    name: "Citizens of Soil",
    description: "Olive oil to get excited about",
    category: "Shopping",
    earnMultiplier: "5x",
    redeemValues: [
      { points: 4735, value: 17.5 },
      { points: 9470, value: 35 },
      { points: 18_940, value: 70 },
    ],
    link: "https://www.citizensofsoil.com/",
  },
  {
    name: "Eleat",
    description: "The high protein, balanced breakfast to fuel your day",
    category: "Shopping",
    earnMultiplier: "5x",
    redeemValues: [
      { points: 3500, value: 17.5 },
      { points: 7000, value: 35 },
      { points: 14_000, value: 70 },
    ],
    link: "https://www.eleatcereal.com/",
  },
  {
    name: "Ministry of Sound Games x Yonder",
    description: "Fitness x nightlife, at Ministry of Sound",
    category: "Fit & Well",
    earnMultiplier: "3x",
    redeemValues: [
      { points: 8670, value: 30 },
      { points: 17_340, value: 60 },
      { points: 34_680, value: 120 },
    ],
    link: "",
  },
  {
    name: "SUKU Saunas",
    description: "Wild sauna and cold plunge experience",
    category: "Fit & Well",
    earnMultiplier: "5x",
    redeemValues: [
      { points: 3375, value: 15 },
      { points: 6750, value: 30 },
      { points: 13_500, value: 60 },
    ],
    link: "",
  },
  {
    name: "Lana del Rey",
    description: "Lana del Rey live at Wembley",
    category: "Events",
    earnMultiplier: "3x",
    redeemValues: [
      { points: 11_250, value: 45 },
      { points: 22_500, value: 90 },
      { points: 45_000, value: 180 },
    ],
    link: "",
  },
  {
    name: "58 & CO Gin Masterclass",
    description: "Distil your very own bottle of gin",
    category: "Events",
    earnMultiplier: "5x",
    redeemValues: [
      { points: 7315, value: 62.5 },
      { points: 14_630, value: 125 },
      { points: 29_260, value: 250 },
    ],
    link: "",
  },
  {
    name: "The Great Gatsby",
    description: "Award-winning musical inspired by the classic American novel",
    category: "Events",
    earnMultiplier: "3x",
    redeemValues: [
      { points: 6800, value: 30 },
      { points: 13_600, value: 60 },
      { points: 27_200, value: 120 },
    ],
    link: "",
  },
  {
    name: "Freddie's Flowers",
    description: "Hand-picked fresh flowers, inspired by the seasons",
    category: "Shopping",
    earnMultiplier: "5x",
    redeemValues: [
      { points: 2755, value: 12.5 },
      { points: 5510, value: 25 },
      { points: 11_020, value: 50 },
    ],
    link: "",
  },
  {
    name: "Stubble & Co",
    description: "Multi-functional bags that enable you to Do.More.",
    category: "Shopping",
    earnMultiplier: "5x",
    redeemValues: [
      { points: 6300, value: 30 },
      { points: 12_600, value: 60 },
      { points: 25_200, value: 120 },
    ],
    link: "",
  },
  {
    name: "SUBI",
    description: "Designed for every element",
    category: "Shopping",
    earnMultiplier: "5x",
    redeemValues: [
      { points: 5535, value: 25 },
      { points: 11_070, value: 50 },
      { points: 22_140, value: 100 },
    ],
    link: "",
  },
  {
    name: "Good Cake Day",
    description: "Brownies and Cakes for All Occasions",
    category: "Shopping",
    earnMultiplier: "5x",
    redeemValues: [
      { points: 3950, value: 16.25 },
      { points: 7900, value: 32.5 },
      { points: 15_800, value: 65 },
    ],
    link: "",
  },
  {
    name: "Estrid",
    description: "Award-winning hair removal and body care",
    category: "Shopping",
    earnMultiplier: "5x",
    redeemValues: [
      { points: 1325, value: 5 },
      { points: 2650, value: 10 },
      { points: 5300, value: 20 },
    ],
    link: "",
  },
  {
    name: "DELLI",
    description: "A platform to shop the best independent food and drink",
    category: "Shopping",
    earnMultiplier: "5x",
    redeemValues: [
      { points: 3260, value: 15 },
      { points: 6520, value: 30 },
      { points: 13_040, value: 60 },
    ],
    link: "",
  },
  {
    name: "MONC",
    description: "On a mission to reframe the eyewear industry",
    category: "Shopping",
    earnMultiplier: "5x",
    redeemValues: [
      { points: 11_265, value: 50 },
      { points: 22_530, value: 100 },
      { points: 45_060, value: 200 },
    ],
    link: "",
  },
  {
    name: "Batch LDN",
    description: "Casual Suits made-to-order in London",
    category: "Shopping",
    earnMultiplier: "5x",
    redeemValues: [
      { points: 20_000, value: 100 },
      { points: 40_000, value: 200 },
      { points: 80_000, value: 400 },
    ],
    link: "",
  },
  {
    name: "Allpress Coffee online",
    description: "Speciality coffee roasted for your kitchen",
    category: "Shopping",
    earnMultiplier: "5x",
    redeemValues: [
      { points: 2800, value: 14 },
      { points: 5600, value: 28 },
      { points: 11_200, value: 56 },
    ],
    link: "",
  },
  {
    name: "58 & CO",
    description: "Female-founded, sustainable, British spirits",
    category: "Shopping",
    earnMultiplier: "5x",
    redeemValues: [
      { points: 5155, value: 20 },
      { points: 10_310, value: 40 },
      { points: 20_620, value: 80 },
    ],
    link: "",
  },
  {
    name: "Nonna Tonda",
    description: "Fresh pasta and delicious sauces delivered",
    category: "Shopping",
    earnMultiplier: "5x",
    redeemValues: [
      { points: 3025, value: 12.5 },
      { points: 6050, value: 25 },
      { points: 12_100, value: 50 },
    ],
    link: "",
  },
  {
    name: "Gymkhana Fine Foods",
    description: "The Michelin-starred experience, at home",
    category: "Shopping",
    earnMultiplier: "5x",
    redeemValues: [
      { points: 5225, value: 19 },
      { points: 10_450, value: 38 },
      { points: 20_900, value: 76 },
    ],
    link: "",
  },
  {
    name: "BAO",
    description: "Pillowy bao buns, Taiwanese fried chicken and bubble tea",
    category: "Dining",
    earnMultiplier: "5x",
    redeemValues: [
      { points: 5445, value: 20 },
      { points: 10_890, value: 40 },
      { points: 21_780, value: 80 },
    ],
    link: "",
  },
  {
    name: "Jam Delish",
    description: "Family-owned vegan Caribbean restaurant and cocktail bar",
    category: "Dining",
    earnMultiplier: "5x",
    redeemValues: [
      { points: 6300, value: 25 },
      { points: 12_600, value: 50 },
      { points: 25_200, value: 100 },
    ],
    link: "",
  },
  {
    name: "The Water House Project",
    description: "Simple yet surprising social fine dining",
    category: "Dining",
    earnMultiplier: "5x",
    redeemValues: [
      { points: 19_625, value: 77.5 },
      { points: 39_250, value: 155 },
      { points: 78_500, value: 310 },
    ],
    link: "",
  },
  {
    name: "POLPO",
    description: "Venetian-style sharing plates",
    category: "Dining",
    earnMultiplier: "5x",
    redeemValues: [
      { points: 5400, value: 22.5 },
      { points: 10_800, value: 45 },
      { points: 21_600, value: 90 },
    ],
    link: "",
  },
  {
    name: "Albers",
    description: "Café by day, bistro-style restaurant in the evenings",
    category: "Dining",
    earnMultiplier: "5x",
    redeemValues: [
      { points: 5955, value: 25 },
      { points: 11_910, value: 50 },
      { points: 23_820, value: 100 },
    ],
    link: "",
  },
  {
    name: "Calong",
    description: "Neighbourhood gem offering a mix of Korean and European",
    category: "Dining",
    earnMultiplier: "5x",
    redeemValues: [
      { points: 9850, value: 35 },
      { points: 19_700, value: 70 },
      { points: 39_400, value: 140 },
    ],
    link: "",
  },
  {
    name: "Lahpet",
    description: "One of London's only restaurants championing Burmese cooking",
    category: "Dining",
    earnMultiplier: "5x",
    redeemValues: [
      { points: 7050, value: 25 },
      { points: 14_100, value: 50 },
      { points: 28_200, value: 100 },
    ],
    link: "",
  },
  {
    name: "Kinkally",
    description: "European fusion championing khinkali, the Georgian dumpling",
    category: "Dining",
    earnMultiplier: "5x",
    redeemValues: [
      { points: 12_650, value: 45 },
      { points: 25_300, value: 90 },
      { points: 50_600, value: 180 },
    ],
    link: "",
  },
  {
    name: "Bar Kinky",
    description: "Kinkally's subterranean inventive cocktail den",
    category: "Dining",
    earnMultiplier: "5x",
    redeemValues: [
      { points: 6950, value: 25 },
      { points: 13_900, value: 50 },
      { points: 27_800, value: 100 },
    ],
    link: "",
  },
  {
    name: "Gouqi",
    description: "Multi award-winning Chinese fine dining from Tong Chee Hwee",
    category: "Dining",
    earnMultiplier: "5x",
    redeemValues: [
      { points: 11_050, value: 40 },
      { points: 22_100, value: 80 },
      { points: 44_200, value: 160 },
    ],
    link: "",
  },
  {
    name: "Hainan House",
    description:
      "Southern Chinese Cuisine with inspirations from Hainan Island",
    category: "Dining",
    earnMultiplier: "5x",
    redeemValues: [
      { points: 4325, value: 15 },
      { points: 8650, value: 30 },
      { points: 17_300, value: 60 },
    ],
    link: "",
  },
  {
    name: "Alfonsina",
    description: "Latin American joined with pure, honest & fresh ingredients",
    category: "Dining",
    earnMultiplier: "5x",
    redeemValues: [
      { points: 6950, value: 25 },
      { points: 13_900, value: 50 },
      { points: 27_800, value: 100 },
    ],
    link: "",
  },
  {
    name: "Potter & Reid",
    description: "Breakfast & lunch, premium coffee & natural wines",
    category: "Dining",
    earnMultiplier: "5x",
    redeemValues: [
      { points: 2150, value: 7.5 },
      { points: 4300, value: 15 },
      { points: 8600, value: 30 },
    ],
    link: "",
  },
  {
    name: "Chakra",
    description: "North Indian cuisine with Punjabi influences",
    category: "Dining",
    earnMultiplier: "5x",
    redeemValues: [
      { points: 5700, value: 20 },
      { points: 11_400, value: 40 },
      { points: 22_800, value: 80 },
    ],
    link: "",
  },
  {
    name: "Miznon Erev",
    description: "Evening dining concept at beloved Mediterranean spot",
    category: "Dining",
    earnMultiplier: "5x",
    redeemValues: [
      { points: 11_250, value: 40 },
      { points: 22_500, value: 80 },
      { points: 45_000, value: 160 },
    ],
    link: "",
  },
];
